### PR TITLE
solution of day 3 easy problem

### PR DESCRIPTION
**Pull request by Tanishq112005**
## Description
in the function1()  efficiently compute and output a maximum frequency of consecutive elements in two arrays, p[] and q[]. It optimizes the algorithm by tracking the maximum frequency encountered for each element and updating the answer accordingly,

## Semver Changes

- [x] Patch (bug fix, no new features)
- [ ] Minor (new features, no breaking changes)
- [ ] Major (breaking changes)

## Issues

#19

## Checklist

- [x] I have read the [Contributing Guidelines](../Contributor_Guide/Contruting.md).

### CODE REVIEW

**Review by sanghaibiraj — APPROVED** [review]
LGTM

**Comment by sanghaibiraj** [comment]
@Tanishq112005 please follow the commiting rules.
header must not be longer than 100 characters, current length is 171 [header-max-length]
subject may not end with full stop [subject-full-stop]
No capital letters should be used
subject and type must not be empty

**Comment by sanghaibiraj** [comment]
just write "feat: solved day 3 easy" in commit message and it would work

**Comment by Tanishq112005** [comment]
ok sir

**Pull request closed without merging**
