### PR TITLE
chore: completed day5 medium task

### LINKED ISSUE #31: [Question]: Solve Medium/Day5 Task.
### So, what is it about?

Visit the medium/day_5 folder, check out the problem.txt file and solve the question.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Ankur-Dwivedi22**
## Description

>Completed day5 medium task.

## Semver Changes

- [ ] Patch (bug fix, no new features)
- [ ] Minor (new features, no breaking changes)
- [ ] Major (breaking changes)

## Issues

> List any issues that this pull request closes.

## Checklist

- [ ] I have read the [Contributing Guidelines](../Contributor_Guide/Contruting.md).

### CODE REVIEW

**Review by sanghaibiraj — CHANGES_REQUESTED** [review]
Please don't add any extra folder. remove the .cph folder you have added

**Comment by Ankur-Dwivedi22** [comment]
removed extra folder( .cph was added automatically, don't know the reason).

**Review by sanghaibiraj — CHANGES_REQUESTED** [review]
Since its medium level, i expect you to do it in a better time complexity

**Comment by Ankur-Dwivedi22** [comment]
Done in better time complexity.

**Review by sanghaibiraj — APPROVED** [review]
LGTM

**Pull request merged**
