### PR TITLE
Updated Solution Of day 3 of easy problem

### PR DESCRIPTION
**Pull request by Tanishq112005**
### Description
In the function1() of the code to efficiently compute and output a maximum frequency of consecutive elements in two arrays, p[] and q[]. It optimizes the algorithm by tracking the maximum frequency encountered for each element and updating the answer accordingly.

### Semver Changes

- [x]  Patch (bug fix, no new features)
- [ ] Minor (new features, no breaking changes)
- [ ] Major (breaking changes)

Issues
#19 

Checklist
 I have read the [Contributing Guidelines](https://github.com/OPCODE-Open-Spring-Fest/codecrack/blob/main/.github/Contributor_Guide/Contruting.md).

### CODE REVIEW

**Review by sanghaibiraj — APPROVED** [review]
LGTM

**Comment by sanghaibiraj** [comment]
@Tanishq112005 you code is correct but your pr format is wrong. please recheck and send your pr again

**Comment by Tanishq112005** [comment]
@sanghaibiraj The Pull Request has been updated

**Comment by sanghaibiraj** [comment]
Sorry @Tanishq112005 , its still failing commitlint checks. please check the commiting.md file for reference.

**Comment by sanghaibiraj** [comment]
its still showing error @Tanishq112005 . i guess capital letters are not allowed

**Comment by sanghaibiraj** [comment]
I also suggest you to not continue in this pr and send a different pr

**Pull request closed without merging**
