### PR TITLE
feat: solved day8 medium

### PR DESCRIPTION
**Pull request by Jagpreet153**
## Description

> Approach in Comments
## Semver Changes

- [x] Patch (bug fix, no new features)
- [ ] Minor (new features, no breaking changes)
- [ ] Major (breaking changes)

## Issues

> #47 

## Checklist

- [x] I have read the [Contributing Guidelines](../Contributor_Guide/Contruting.md).

### CODE REVIEW

**Comment by bluemincoder** [comment]
@Jagpreet153 your solution is wrong, do you want to retry? comment in issues.

**Comment by Jagpreet153** [comment]
@minaal07 Can you give some information about the incorrect testcases

**Review by bluemincoder — CHANGES_REQUESTED** [review]
Runtime errors occurred in many test cases. Would you like to retry? Please comment in the issues.

**Comment by sanghaibiraj** [comment]
@Jagpreet153 you have been unassigned from this issue.

**Pull request closed without merging**
