### PR TITLE
Update solution.cpp

### PR DESCRIPTION
**Pull request by guptanshuman124**
added solution to the problem

## Description

> medium problem of day 11 

## Semver Changes

- [ ] Patch (bug fix, no new features)
- [ ] Minor (new features, no breaking changes)
- [x] Major (breaking changes)

## Issues

> List any issues that this pull request closes.

## Checklist

- [x] I have read the [Contributing Guidelines](../Contributor_Guide/Contruting.md).

### CODE REVIEW

**Comment by sanghaibiraj** [comment]
please mention the day and level

**Comment by guptanshuman124** [comment]
> please mention the day and level

@sanghaibiraj the problem is day 11 / medium

i have updated in the description of my pr .

**Review by sanghaibiraj — COMMENTED** [review]
Sorry, your solution is wrong.
example test case
input
4
615664
916441
627600
279508

correct output
1
2
3
2

your output
2
7
3
5

**Comment by sanghaibiraj** [comment]
@guptanshuman124 if you want to retry, please comment in issues section

**Pull request closed without merging**
