### PR TITLE
solved easy day9 problem

### PR DESCRIPTION
**Pull request by Omji-Kesharwani**
## Description

> Give a brief description of the pull request.

## Semver Changes

- [ ] Patch (bug fix, no new features)
- [ ] Minor (new features, no breaking changes)
- [ ] Major (breaking changes)

## Issues

> List any issues that this pull request closes.

## Checklist

- [x] I have read the [Contributing Guidelines](../Contributor_Guide/Contruting.md).

### CODE REVIEW

**Comment by bluemincoder** [comment]
@Omji-Kesharwani Your solution is wrong, do you want to retry? comment in issues

**Comment by Omji-Kesharwani** [comment]
sir in which test case the output is coming wrong

**Comment by minaal07** [comment]
> sir in which test case the output is coming wrong

Input
0
00
Output
OK

Answer
WRONG_ANSWER

**Review by bluemincoder — COMMENTED** [review]
wrong on test case:

Input
0
00
Output
OK
Answer
WRONG_ANSWER

**Comment by Omji-Kesharwani** [comment]
Sir but in the question it is mentioned that input does not contain any leadiing zeros.

**Comment by Omji-Kesharwani** [comment]
sir but i have tried gain plzz check it

**Comment by bluemincoder** [comment]
> Sir but in the question it is mentioned that input does not contain any leadiing zeros.

Check properly it says that if you Shuffle the digits in this number in order to obtain the smallest possible number without leading zeroes.  but here you don't need to shuffle.

**Review by bluemincoder — CHANGES_REQUESTED** [review]
wrong answer on test case:

Input
666
0666
Output
OK
Answer
WRONG_ANSWER

**Comment by sanghaibiraj** [comment]
@Omji-Kesharwani you are allowed to send a pr only if an issue has been assigned to you. first request in comment of the issue which you want to solve and if the issue is assigned to you then you have to send a pr within the given time frame.

**Pull request closed without merging**
